id: A65049597
title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
type: translation
pechas:
- ID66D2216
- IB7659D41
- I1D11BFCB
- I904754A8
- IE0B62BF2
- I4DD2D446
- I1F40801E
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:37:19.779776
  last_modified_at: 2023-01-04 11:37:19.779791
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  ID66D2216/3E36: 554A
  IB7659D41/4BAE: 554A
  I1D11BFCB/A264: 554A
  I904754A8/5AEE: 554A
  IE0B62BF2/BA6A: 554A
  I4DD2D446/EBCE: 554A
  I1F40801E/4469: 554A
